# Адрес сервера (оставьте как есть)
sonar.host.url=https://sonarcloud.io

# ----> ЭТО ЗАМЕНИТЬ НА СВОЁ <----
# Ваш "логин" (маленькими буквами, как в ссылке Github)
sonar.organization=rensffz
# Уникальное имя проекта (обычно "ваш_логин_имя_репозитория")
sonar.projectKey=rensffz_gis_test

# Откуда брать код для анализа
sonar.sources=lib
sonar.tests=test

# Скажите SonarCloud, откуда взять отчет о покрытии тестов
sonar.dart.coverage.reportsPath=coverage/lcov.info

# ----> НЕ ТРОГАЙТЕ ЭТО - ЭТО ВАЖНО <----
# Игнорируем сгенерированный код, чтобы он не портил статистику
sonar.exclusions=**/*.g.dart, **/*.freezed.dart, **/generated_*.dart
sonar.coverage.exclusions=**/*.g.dart, **/*.freezed.dart, **/*.gr.dart, **/*.g.dart, lib/main.dart