name: Flutter Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Flutter Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'   # убрали точную версию
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Run tests
        run: flutter test --machine > test-results.json
      
      - name: Upload test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          name: Flutter Tests
          path: test-results.json
          reporter: flutter-json